development:
  secret_key_base: secret
  jwt_secret: secret

test:
  secret_key_base: secret
  jwt_secret: secret

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  jwt_secret: <%= ENV["JWT_SECRET"] %>
